### ISSUE TITLE
Nix package now generally available

### ISSUE THREAD

**Issue by cmacrae** [cmacrae/spacebar#10]
👋 Hope you don't mind an issue being opened for this, but I figured it was a good way to notify you and an easy way for people to discover if they were looking for Nix support:

I submitted a [package for spacebar to the nixpkgs repository](https://github.com/NixOS/nixpkgs/pull/86556) the other day. I'm happy to say, following the merge, it is now generally available on the nixpkgs-unstable channel 🎉
```
$ nix-channel --list
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable

$ nix-env -qaP --description spacebar
nixpkgs.spacebar  spacebar-0.5.0  A status bar for yabai tiling window management
```

I've also [submitted a service module](https://github.com/LnL7/nix-darwin/pull/197) to [LnL7/nix-darwin](https://github.com/LnL7/nix-darwin). It lets you configure spacebar like so:
```nix
{
    services.spacebar.enable = true;
    services.spacebar.config = {
      clock_format     = "%R";
      space_icon_strip = "   ";
      text_font        = ''"Helvetica Neue:Bold:12.0"'';
      icon_font        = ''"FontAwesome:Regular:12.0"'';
      background_color = "0xff202020";
      foreground_color = "0xffa8a8a8";
      power_icon_strip = " ";
      space_icon       = "";
      clock_icon       = "";
    };
}
```
Please feel free to simply close this issue :) I just wanted to let you know.  
I'd be happy to submit a PR updating the README, if that's something you'd want

**Comment by somdoron** [comment]
Very cool, yes, please submit a pr to the readme.

**Comment by cmacrae** [comment]
This is now merged and available 🎉   
https://cmacr.ae/post/2020-05-14-spacebar-module-in-nix-darwin-now-generally-available/

I'll submit a PR tomorrow :)
