### ISSUE TITLE
Migrating from yabai

### ISSUE THREAD

**Issue by toyboot4e** [cmacrae/spacebar#11]
Sorry, it's not an "issue", but this is a straight-forward way to enable spacebar.

---
Get the example rc file:

```sh
$ mkdir ~/.config/spacebar
$ # this will overwrite your `spacebarrc` if you have one
$ curl -L https://raw.github.com/somdoron/spacebar/master/examples/spacebarrc > ~/.config/spacebar/spacebarrc
```

Get the latest spacebar:

```sh
$ # WE NEED THE HEAD VERSION (for now; see #6, #8)
$ brew install somdoron/formulae/spacebar --HEAD
```

Let yabai make space for spacebar:

```sh
$ echo '# make space for spacebar' >> ~/.config/yabai/yabairc
$ echo 'yabai -m config top_padding 26' >> ~/.config/yabai/yabairc
```

Now let's start:

```sh
$ brew services start spacebar
```

And confirm the request to use the Accesibility. We're ready!

**Comment by Chandru-B** [comment]
@toyboot4e This works great. Thank you.
I am not able to see the icons though, any idea please?
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           

**Comment by somdoron** [comment]
You probably missing font awesome from brew

**Comment by toyboot4e** [comment]
@Chandru-B Glad to hear that!

The font is probablly installed with this:

```
$ brew tap caskroom/homebrew-fonts
$ brew cask install font-fontawesome
```

And it should work on your desktop (even if you can't see them on your browser).

**Comment by cmacrae** [comment]
I'm closing this issue off, as the information provided here should be straight forward and available in documentation.  
I'll be doing a pass over all the available documentation and noting things like installing from `HEAD` :)

**Comment by 10blackhole** [comment]
anyone can share his spacebarrc config file? pls.
