### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by rcreasey** [cmacrae/spacebar#13]
Not attempting to duplicate functionality from ubersicht or something else super bloated, but are there any plans on providing support for plugins?

For example, I would love to have Apple Music/Spotify currently playing title information displayed in my bar.

**Comment by michalens** [comment]
I think it would be nice to firstly add a functionally on making custom plugins with bash and output them into the bar.

**Comment by rcreasey** [comment]
Yeah, that too would be nice.

**Comment by nzchicken** [comment]
I would like to be able to add an icon to the top right bar based on a key. For example `spacebar -m icon <key> <value>` which would update the icon with the key <key> to the icon of <value>. I'd like to be able to also destroy the icon with something like `spacebar -m icon -d <key>`.

Use case, I run some k8s things, and having the status of a task in a pod would be nice. I can do all the hard stuff with bash myself, but it would be nice to be able to do something like `spacebar -m icon podstatus "Running"` (or use an icon from font-awesome for example). I can thus run the script i have on a cron, or find some better way to trigger it, but either way I'd be able to see the pod status from a glance.

**Comment by cmacrae** [comment]
Sorry @b-n - not sure how I missed your comment here. I quite like the sound of what you're describing. Would you mind perhaps creating a new issue outlining this feature request in detail (if you'd still like to see it!).

As for this issue, I'm considering it resolved as of the introduction of shell outputs in e99329838cd8a5fb19b19705d39366e6d43042ab (soon to be released).

This is a "first-pass" implementation. I plan on making it more flexible, allowing for multiple sections to be defined.
