### ISSUE TITLE
Underlines removal and configurable status line

### ISSUE THREAD

**Issue by fruitless** [cmacrae/spacebar#14]
1. Is it possible to completely remove underlines in spacebar and highlight the active desktop number itself with a color? It's not a feature request, I'm just asking for a little coding guidance, 'cause I don't know C language at all. May be someone can indicate the necessary lines of source code that should be changed to achieve the desired result?

2. It'll be neat to have a configurable central status line. It can be used not only for showing the current active process/window name, but also for music, calendar, command output and whatever else.

**Comment by Eyjafjallajokull** [comment]
As for 1) I was able to remove underlines from date and battery https://github.com/Eyjafjallajokull/spacebar/commit/e352057e7a0b95c7ad208c67c355b5afa126ab9f Changing color for active space will be hard because currently all spaces are displayed as one text element.

**Comment by fruitless** [comment]
Thanks!

**Comment by koekeishiya** [comment]
For point 1, change the following section beginning at line 247:

from
```
            bar_draw_line(bar, space_line, pos.x, pos.y);

            if (sid == space_list[i]) {
                CGPoint new_pos = CGContextGetTextPosition(bar->context);
                struct bar_line mark_line = g_bar_manager.space_underline;
                CGPoint mark_pos = bar_align_line(bar, mark_line, 0, ALIGN_BOTTOM);
                mark_pos.x = mark_pos.x - mark_line.bounds.size.width / 2 - space_line.bounds.size.width / 2;
                bar_draw_line(bar, mark_line, mark_pos.x, mark_pos.y);
                CGContextSetTextPosition(bar->context, new_pos.x, new_pos.y);
            }

```

to

```
            if (sid == space_list[i]) {
                struct rgba_color old_color = space_line.color; // store old color
                space_line.color = rgba_color_from_hex(0xffd75f5f); // override color used
                bar_draw_line(bar, space_line, pos.x, pos.y); // draw line/symbol for active space
                space_line.color = old_color; // restore old color
            } else {
                bar_draw_line(bar, space_line, pos.x, pos.y);
            }
```

**Comment by fruitless** [comment]
Yay, it worked! Thanks!
<img width="1440" alt="spacebar" src="https://user-images.githubusercontent.com/31576554/83904023-d2e64d80-a767-11ea-83ad-243f69e6645a.png">

**Comment by cmacrae** [comment]
FYI, I implemented this - along with configurable space icon colour - in https://github.com/somdoron/spacebar/pull/16, which has been merged to `master` :)

I don't really know C, or the macOS APIs, but I'll hack around and see what I can cook up, regarding the central status line

**Comment by cmacrae** [comment]
Another PR I opened (#17 ) has been merged to `master` that includes "proper" removal of underlines (full removal of the code that handled it, not just passing an empty string to the `bar_prepare_line` function)

**Comment by johnallen3d** [comment]
Along the lines of "configurable status line" (point 2). For now, I'd like to hide the current application/window in the center. Any tips on what I could comment out to accomplish that? I generally rely on space indicators and borders to identify the active window.

**Comment by johnallen3d** [comment]
🤦 I should try reading the code first. I just added `return NULL` to the top of `focused_window_title` and that accomplished what I was looking for.

**Comment by MGCSousa** [comment]
Is this normal? The text does not fit properly, my date has the format of: "%d/%m/%y %R"
In the brew version this does not happened. What might be the problem?

![imagem](https://user-images.githubusercontent.com/17438769/86458303-f677c600-bd1c-11ea-8ef3-759c3f515bfd.png)

**Comment by cmacrae** [comment]
@MGCSousa Yeah, I introduced a bug when I did the underline removal 😬 I haven't had the time yet to address it, but will as soon as I can. It's just a silly error I made in calculating the start position for the power strip

**Comment by yanzhang0219** [comment]
@cmacrae Please fix it, please, please. Thank you~~

**Comment by cmacrae** [comment]
I've opened #20 which should fix that annoying formatting bug 🐛

**Comment by johnallen3d** [comment]
Works like a charm, thanks @cmacrae!

**Comment by johnallen3d** [comment]
Do you have plans to implement item `2` from this request @cmacrae? My dream would be to include current track from `mpc` (for example).

Actually my *real* dream would be to run the current version of the bar at the top of my screen and a second bar at the bottom with `mpc` output.

**Comment by cmacrae** [comment]
I do indeed @johnallen3d 👍 I've kept it in **In progress** on [the project board](https://github.com/cmacrae/spacebar/projects/1), as I plan to work on it when I get some time :)

To simplify things, I'm thinking command (read: shell script) output will be the approach I take.  
That way it makes it very flexible.

**Comment by johnallen3d** [comment]
So exciting! Hadn't noticed you're using the project board feature. 👍 

I agree, shell output would be the most flexible.

**Comment by cmacrae** [comment]
Alright, almost a year later (!) I've finally gotten around to implementing shell output segments in e99329838cd8a5fb19b19705d39366e6d43042ab

These features will be released soon :)

Thank you all for your patience! 🙇
