### ISSUE TITLE
Spaces module not affected by font change

### ISSUE THREAD

**Issue by nwaywood** [cmacrae/spacebar#2]
The `status_bar_text_font` variable is not applying to the spaces module.

To illustrate this issue, I set the font to 18

![image](https://user-images.githubusercontent.com/3773641/78220605-90a55380-750d-11ea-9be8-39034d96c3cc.png)

As you can see, all of the other text in the status bar is size 18 except for the number 1, 2 and 3 in the spaces module which stay the same size no matter what font size I set

**Comment by cmacrae** [comment]
This is because even with regular alphanumeric glyphs for your space "icons", it's still considered the icon font.  
So, you need to set the size in the  `status_bar_icon_font` option (or if you're on recent unreleased versions, just the `icon_font` option).

Hope that makes sense :)

**Comment by cmacrae** [comment]
Courtesy tag (sorry I know it's an old issue - I just inherited project ownership) @nwaywood @knowler @bry-guy

**Comment by bry-guy** [comment]
Thanks - appreciate the response, and thanks for your contributions 😃
