### ISSUE TITLE
[Request for consideration]: Project ownership

### ISSUE THREAD

**Issue by cmacrae** [cmacrae/spacebar#25]
Hey @somdoron 👋   

As I'm sure you've noticed, I've been contributing quite a bit and implementing features people are requesting.  
I'm not sure what your free time/freedom to work on `spacebar` are like of course, but I'd like to float the idea of possibly transferring the project over to my GitHub.  

I intend to continue working on `spacebar` and it'd be nice to be able to handle releases and would fit nicely with my Nix package maintenance.

Of course, I don't want to encroach, so I do hope you understand this is an open dialogue coming from a good place :)

**Comment by somdoron** [comment]
@cmacrae of course, no problem. You need to remove your fork before I can do that

**Comment by cmacrae** [comment]
Ah, thank you! I really appreciate that you're so open to this 🙏   
I've removed my fork, so you should be able to transfer it :)

**Comment by cmacrae** [comment]
🎉 All sorted! Thanks @somdoron 🙇

**Comment by somdoron** [comment]
There is a closed issue in yabai referencing the project, you might want to add a comment with the new url.

Good luck!

**Comment by cmacrae** [comment]
Good shout 👍 Thanks again! I hope to see contributions from you in the future :)
