### ISSUE TITLE
long window title will mess the right section

### ISSUE THREAD

**Issue by yanzhang0219** [cmacrae/spacebar#26]
I stumbled across this issue when I shopped in Amazon. I found that if the window title is too long, it will occupy the room of the right part, i.e., the charging status and time section. I attached a screenshot below: 

![image](https://user-images.githubusercontent.com/11582667/87606379-b49d3700-c6af-11ea-9841-fedeb4b8166d.png)

Thank you.

**Comment by cmacrae** [comment]
Thanks for reporting this @yanzhang0219 👍 Coincidentally, I only stumbled upon this for the first time a cuple days ago too!  

I'll look into this soon

**Comment by cmacrae** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3392199/87830682-7eabae80-c879-11ea-940f-9a16fef64bdc.png">

There you go @yanzhang0219 🙃 Titles greater than 100 characters are truncated and appended with `...`

**Comment by yanzhang0219** [comment]
@cmacrae This is really nice!! 👍 
Thank you!

**Comment by johnallen3d** [comment]
@cmacrae - Thank you!!! I've had this on my list to report for ages (when this bar was part of Yabai)! 😁

**Comment by cmacrae** [comment]
No problem! It was an annoying bug :)

**Comment by cmacrae** [comment]
My solution to this introduced a bug 🐛 Fortunately @yanzhang0219 opened #28 and I fixed it.  
Just noting this here for reference ✍️
