### ISSUE TITLE
Just want to say "THANK YOU"

### ISSUE THREAD

**Issue by yanzhang0219** [cmacrae/spacebar#27]
Thank you @cmacrae for taking over this project, an essential for our yabai users.
Thank you for such an active development to improve and perfect it in your spare time. 
Thank you for your responsiveness to our requests.
Thank you for your great organization so that we can keep tracking of the progress of the development. 
Thank you very much!

You can feel free to close this! :)

**Comment by cmacrae** [comment]
Aw, thank you very much @yanzhang0219 🙏 This means a lot!
