### ISSUE TITLE
Bar disappears for some window title

### ISSUE THREAD

**Issue by yanzhang0219** [cmacrae/spacebar#28]
macOS version: 10.15.6 (the latest)
spacebar: the latest master

I came across this issue when I browsed this website using Chrome, https://www.v2ex.com/t/691049#reply3. You could see that the bar disappears. But, if I open it using Safari, the bar works well. (Another example website: https://www.v2ex.com/t/691070#reply0)

![image](https://user-images.githubusercontent.com/11582667/87843137-d856ad80-c866-11ea-85e2-dbefb672ecb5.png)

Initially, I suspected that this issue happened for the window title containing Chinese words and is very long, however, I tested this website, https://www.v2ex.com/t/691061#reply19, and I found the bar didn't disappear (using Chrome). But, if I open this website using Safari, the bar disappears (interesting...hum...). That's weird. Another thing is that even though the bar works well for this website using Chrome, the bar only shows a few words and it actually still has many rooms for more words.

![image](https://user-images.githubusercontent.com/11582667/87843437-a7c44300-c869-11ea-960a-adab81e2ca35.png)

So far I found this issue only happens for the window title including Chinese words (I don't know whether or not the Chinese words cause this issue but it is very likely). I am not sure whether it would happen for some window title containing all English words.

What's more, for some long window title, the bar only shows one word, i.e., it is truncated right after the first word. For example, try this website, https://www.geeksforgeeks.org/must-do-coding-questions-for-companies-like-amazon-microsoft-adobe/. (only happens for Chrome, not Safari)

![image](https://user-images.githubusercontent.com/11582667/87843350-cece4500-c868-11ea-869f-eae3951ad17f.png)

Furthermore, 100 characters are good for English words, i.e., it can contain many words, but for Chinese words, I think it is not enough as the second screenshot above shows, the bar only shows very few Chinese words. 

Sorry for my long statement, and thank you very much.

**Comment by cmacrae** [comment]
Thanks for the thorough bug report @yanzhang0219 ! 🙌 Certainly no need to apologise, this is all really useful info 🤗 

Yes, I saw this bug yesterday when I was fixing the long title issue - I thought I'd solved it with [this check](https://github.com/cmacrae/spacebar/blob/master/src/bar.c#L181), but you're right, I've just installed Chrome and tried that link and I get the bug too 🐛   

These links you've provided are really helpful in debugging - some really strange behaviour I've just seen:

* Chrome with https://www.v2ex.com/t/691049#reply3 💔 breaks
* Firefox with https://www.v2ex.com/t/691049#reply3 💚 works
* Safari with https://www.v2ex.com/t/691049#reply3 💚 works
* Chrome with https://www.v2ex.com/t/691061#reply19 💚 works
* Firefox with https://www.v2ex.com/t/691061#reply19 💔 breaks
* Safari with https://www.v2ex.com/t/691061#reply19 💔 breaks

Very strange indeed...

I agree regarding the 100 character issue with non-English languages. I had initially thought "I'll calculate the available draw space and truncate based on that" but had decided "100 chars is *probably* fine", but it appears that was a bit naive of me!

Thanks again for the info you've provided, it's given me a really good basis to test things on 👍

**Comment by cmacrae** [comment]
There are some overlap mechanisms already in place that don't appear to be working.  
So, I think I'll undo my changes to `focused_window_title()` and look to fix it there. This will lend itself to future functionality where the centre strip serves as a space for other information too :)

I'll hopefully be able to fix this today 🤞

**Comment by cmacrae** [comment]
Fixed in eb347cc 🎉   
I fixed the overlap logic and removed the "> 100 chars" solution I'd implemented that introduced this bug.

It now works happily with all the above scenarios.
Thanks again for the thorough bug report @yanzhang0219 - it made debugging and fixing this a lot easier! 🙏

**Comment by yanzhang0219** [comment]
Thank you 😊 
I am really glad to be a tester, making some contributions and assisting you to make the project much more shining 🤝

Additional thoughts:
So far, for a very long title, it will occupy the whole empty spaces of the bar (i.e., it is right next to the left "space" section and the right "status" section). It looks a little crowded, and not convenient for a widescreen.

![image](https://user-images.githubusercontent.com/11582667/87856755-01625700-c8d6-11ea-9f8c-f17c3f5ea377.png)

Thought-1: Center the title, i.e., place some spaces (fixed length) on each side of the title, and if the title is too long, it can be truncated on its right

![image](https://user-images.githubusercontent.com/11582667/87857044-7b93db00-c8d8-11ea-8479-0b8776c69075.png)

Thought-2: Place the title on one side with a fixed length (say on the left next to the "space" section), and then we will have extra rooms for other info that will be implemented in the future.

![image](https://user-images.githubusercontent.com/11582667/87857172-771bf200-c8d9-11ea-82ef-124bc26b8367.png)

What's your opinion? Thank you. 😃

**Comment by cmacrae** [comment]
Well, I'm very happy to have you on board testing 🙌   

Yep! So, funnily enough, 'Thought-1' is actually something I implemented as part of the changes in eb347cc already, haha.  
Just not enough, I think. I agree - it does look messy. I'll add some more padding 👍   

Left aligned title is certainly something I could implement, but would introduce more complexity than I'd care for at the moment, as I'll likely be playing around with the center strip for other things very soon :)

Thanks for your thoughts!

P.S: Love these diagrams! What did you use to make them?

**Comment by cmacrae** [comment]
@yanzhang0219 I just pushed afa0db1 to [enhancement/long_title_padding](https://github.com/cmacrae/spacebar/tree/enhancement/long_title_padding) - see what you think :)

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3392199/87859049-49ab6480-c92a-11ea-9123-0a67b04c9faa.png">

**Comment by yanzhang0219** [comment]
Wow, it does look much prettier 👍 Thank you!

> I'll likely be playing around with the center strip for other things very soon :)

Very much looking forward to it and cannot wait to play with it 🤩

> P.S: Love these diagrams! What did you use to make them?

I am using an app called Notability in iPad with Apple Pencil. After drawing the diagram on the iPad, I just need to select it and copy it, and then I can paste it on my mac directly by means of Apple's Universal Clipboard.

**Comment by cmacrae** [comment]
>Wow, it does look much prettier 👍 Thank you! You could still put ... at the end if it is truncated as you implemented before. Are you gonna merge it to master, or conduct more testing?

Glad you like it :) I will consider adding `...` to truncated titles, but at the moment it's more hassle than it's worth, I feel. This implementation doesn't touch the value retrieved from `focused_window_title()` like my last one (that introduced the bug) - it instead changes the draw space, which is a much nicer solution, but also means less flexibility with manipulating the title value.

I'll merge it to master 👍 

> Very much looking forward to it and cannot wait to play with it 🤩

😁 

> I am using an app called Notability in iPad with Apple Pencil. After drawing the diagram on the iPad, I just need to select it and copy it, and then I can paste it on my mac directly by means of Apple's Universal Clipboard.

Nice! I have an iPad and Apple Pencil too 👌 I'm definitely going to use this workflow - thanks for sharing!
