### ISSUE TITLE
Space information for all monitors on each monitor

### ISSUE THREAD

**Issue by nwaywood** [cmacrae/spacebar#3]
First of all, thank you so much for this project! 

Before I switched to spacebar I was using an ubersicht bar where my spaces widget looked like this:

![image](https://user-images.githubusercontent.com/3773641/78221481-2ee5e900-750f-11ea-9bd0-26d5f978bd1c.png)

This indicates:
- Spaces 1, 2 and 3 are on monitor 1, and space 2 is the active space
- `-` is a visual separator for monitors
- Spaces 4 and 5 are on monitor 2, and space 5 is the active space
- This widget will therefore look the same on all monitors

Any chance it would be possible to add a new option to specify if you want the spaces module to display spaces "per monitor" (like it is currently implemented) or "all" like my screenshot above?

Thanks again

**Comment by cmacrae** [comment]
Hey @nwaywood 👋 Almost a year later! Sorry for such a delayed response, I've been on hiatus.  
This'd be a really nice feature 👍 I'll prioritise this next and include it in the next release (soon).

Thanks for the kind words, I hope you're still enjoying using spacebar!

**Comment by cmacrae** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/3392199/113353495-a8d4cc00-9335-11eb-977b-94d12ac9b21d.png">

This is what I've whipped up so far :) In this example there's 3 displays each with 3 spaces  

I've implemented an optional separator and additional `space_icon_color_secondary` & `space_icon_color_tertiary` options which allow for a different colour based on the display the spaces occupy.

The extra `space_icon_color_*` options are sort of crude. I'd rather implement a `space_icon_colors` option which could work on a space separated index like the `_strip` options: `space_icon_colors = 0xffffab91 0xff78c4d4 0xfffff9b0`

**Comment by cmacrae** [comment]
Done in 1b0d1d644f11f20d96c290bd05b1157eb55f4ca9 :)This'll be available in the next release (soon)
