### ISSUE TITLE
Space between 2 values

### ISSUE THREAD

**Issue by aklsh** [cmacrae/spacebar#30]
Hey,
I just started using `spacebar`, and I'm loving it! One thing I would really like is to space out the values like date, time, power etc. Right now, it looks very congested to me (see screenshot below). I tried going through the man page, but I couldn't find any entry for this. I even tried to make the icons as a string in quotes and including the space in that, but that messed up the spacing even more (see below).

Is there any possibility of setting the spacing on our own? Another feature I would like is setting the position of the values by the user - Like date and time on the left, battery on the right etc.

Without spacing in icons:
![Screenshot 2020-08-05 at 8 31 56 AM](https://user-images.githubusercontent.com/45280368/89367501-d0b45700-d6f6-11ea-8a02-33af841ac735.png)

With spacing in icons ("  "):
![Screenshot 2020-08-05 at 8 35 10 AM](https://user-images.githubusercontent.com/45280368/89367503-d1e58400-d6f6-11ea-844b-0edc86f82499.png)

**Comment by yanzhang0219** [comment]
@cmacrae said spacebar will finally support plugins and I believe we could freely organize the items once the plugin feature comes out. :) Let's stay tuned.

**Comment by aklsh** [comment]
Ah. Alright then.

**Comment by yanzhang0219** [comment]
It is already in the todo list here (https://github.com/cmacrae/spacebar/projects/1). But I think it needs lots of work. Hope we could see it soon.

**Comment by cmacrae** [comment]
Thanks for chiming in here @yanzhang0219 🤗   

Hey @aklsh 👋 Thanks for opening this issue! I hope to get some time to implement the "plugin" feature soon, and actually I  hadn't concretely planned out layout positioning, but it's certainly achievable - I think I'd do it separately from the "plugin" feature.  

Regarding the spacing, though - I think that's a valid request, and already have the lines in my head to implement it :)

**Comment by cmacrae** [comment]
Whipped this up @aklsh @yanzhang0219 
![](https://i.imgur.com/XPXXQCU.gif)

What d'you think? :) Should there be a separate setting for spacing in the left and the right?

**Comment by yanzhang0219** [comment]
Nice 👍. Haha. Yeah, I think a separate setting for the left and the right section will be better. Thank you.

**Comment by cmacrae** [comment]
Alright, this is implemented in 4eaab76 with `spacing_left` and `spacing_right` options :)  
It'll be included in the next release

**Comment by yanzhang0219** [comment]
Great!!! 👊 I will try it when it is merged to master. Thank you for your work.

**Comment by cmacrae** [comment]
My pleasure! It's on `master` now 👌

**Comment by aklsh** [comment]
Sorry, couldn't comment sooner. This is exactly what I wanted!!

**Comment by cmacrae** [comment]
No problem @aklsh 😁 Glad it's what you wanted - if you want that feature now, you can install from `HEAD`.  
Otherwise, I'll include it in the next release 🙃
