### ISSUE TITLE
Option to hide the current application's title from a config value?

### ISSUE THREAD

**Issue by Norviah** [cmacrae/spacebar#31]
Would it be possible to hide the current application's title from a config value, maybe something like `spacebar -m config title <on|off>`? 

Apologies as I would try to figure out how to implement and do a pull request, but I have no idea on how to work with C, although I will still try to implement it but I'd thought I'd make an Issue in case if someone who is more experienced in C would be down to implement it.

**Comment by johnallen3d** [comment]
I'm in the same boat (not knowing C) and don't know how to make it configurable. But I was able to manually disable the application title. https://github.com/cmacrae/spacebar/issues/14#issuecomment-648341920

**Comment by Norviah** [comment]
yee i saw that but i thought if it would be possible through a config option, so we don't have to edit the source when updates happen

**Comment by Norviah** [comment]
I've tried my best to implement this and made a pull request [here](https://github.com/cmacrae/spacebar/pull/32).
