### ISSUE TITLE
Unrelated question

### ISSUE THREAD

**Issue by Jarvvski** [cmacrae/spacebar#34]
What are you using as a web browser in the provided screenshot, as well as removing the 'traffic lights' from the other windows

![image](https://user-images.githubusercontent.com/6012840/92702001-b73fa400-f361-11ea-8949-1da36c1686a0.png)

**Comment by 2m** [comment]
Would like to know this as well. :)

**Comment by johnallen3d** [comment]
Not OP but I'd say that's [qutebrowser](https://qutebrowser.org/).

**Comment by cmacrae** [comment]
Hey @Jarvvski @2m @johnallen3d 👋 Sorry for such a late response! I've been on hiatus  

It's actually Firefox! I write about how I achieve this in [this blog post](https://cmacr.ae/post/2020-05-09-managing-firefox-on-macos-with-nix/). My current userChrome.css is here:
https://github.com/cmacrae/config/blob/master/conf.d/userChrome.css

I've kept it commented, so you should be able to find the bits relevant to what you want to achieve (if you end up using Firefox)
