### ISSUE TITLE
Getting space_icon_strip sets it to empty.

### ISSUE THREAD

**Issue by jraregris** [cmacrae/spacebar#35]
I want to get the value of `space_icon_strip`, but when i call `spacebar -m config space_icon_strip`, I get no output, and all the space icons are set to `*`.

I expected it to output the value of `space_icon_strip` in the same way `spacebar -m config space_icon` outputs `*`.

Is this a bug, or am I misunderstanding the intended behavior?

**Comment by cmacrae** [comment]
Thanks very much for raising this, and the PR! 🙌  That is indeed a bug 🐛   
I'll hop over to the PR and check it out 🙃
