### ISSUE TITLE
Spacebar with nerfont

### ISSUE THREAD

**Issue by nilsi** [cmacrae/spacebar#37]
Hi,

Thank you for this project!
I wonder is it possible to make it work with nerd font? I don't get any icons in my bar, unfortunately.

Config:
![Screenshot 2020-10-07 at 09 04 13](https://user-images.githubusercontent.com/793881/95298254-14a11500-087c-11eb-88fc-9df6e430c438.png)

I didn't get any icons before either when i manually tried to install font-awesome.

**Comment by JaeHeyK** [comment]
Did you check **Nerd Fonts cheatsheet?**
https://www.nerdfonts.com/cheat-sheet

Copying the icon and pasting it works for me!
<img width="1280" alt="스크린샷 2020-10-07 오후 4 28 27" src="https://user-images.githubusercontent.com/24244326/95300688-75e7d900-08ba-11eb-9b58-6cd64e4e089d.png">
I used "Victor Mono Nerd Font".

**Comment by nilsi** [comment]
I got it working, thank you! I think changing to Mono helped for me
```

#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "Hack Nerd Font Mono:Regular:12.0"
spacebar -m config background_color   0xff202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff458588
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip   I II III IV V VI VII VIII IX X
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%d/%m/%y %R"

echo "spacebar configuration loaded.."

```
