### ISSUE TITLE
How To set bar transparency

### ISSUE THREAD

**Issue by YandexLeetCode** [cmacrae/spacebar#38]

**Comment by yanzhang0219** [comment]
Please search the already existing issues before you ask a question.

**Comment by typkrft** [comment]
@YandexLeetCode  it is in ARBG format. You can see [this post for more](https://github.com/cmacrae/spacebar/issues/19#issuecomment-653863825). First two bits are your alpha then red then blue then green in hex.

**Comment by YandexLeetCode** [comment]
@yanzhang0219 ok
