### ISSUE TITLE
Add option to configure left and right spacing 

### ISSUE THREAD

**Issue by noib3** [cmacrae/spacebar#44]
It'd be nice to be able to configure the spacing between the left edge of the screen and the first space icon, and between the clock and the right edge of the screen.

Note that I'm not talking about `spacebar -m config spacing_left` and `spacebar -m config spacing_right`, those only control the spacing *between* the blocks, not the spacing between the first (last) block and the left (right) edge of the screen.

**Comment by cmacrae** [comment]
Hey @noib3 👋 Thanks for the feature request. Sure, that sounds like a nice-to-have :) I can whip that up right now

**Comment by cmacrae** [comment]
There you go, added in c9305dd :)
