### ISSUE TITLE
possible typo in man page

### ISSUE THREAD

**Issue by kabirbg** [cmacrae/spacebar#45]
I'd like to start by letting you know that this is a wonderful project, and I really appreciate the work that has gone into making this work. I think there might be a typo in the man page... [man spacebar](https://github.com/cmacrae/spacebar/blob/master/doc/spacebar.asciidoc) tells me, under "DESCRIPTION", that `spacebar is a tiling window manager for macOS based on binary space partitioning.` I wonder if this was copied from the yabai man page and not edited; I believe it should read instead something more like 'spacebar is a minimal status bar for macOS ideal for use with tiling window managers like yabai.' Thanks! (edit: thanks for the pull request, merging that should fix the issue!)

**Comment by cmacrae** [comment]
Whoops! Thanks pointing this out! I noticed it the other day. It's fixed on master and will be included in the next release :)
