### ISSUE TITLE
Spacebar only on one display?

### ISSUE THREAD

**Issue by 24unix** [cmacrae/spacebar#47]
Is there an option to have the Spacebar only on one Display?

**Comment by cmacrae** [comment]
Hey @24unix 👋 Sorry for the delayed response - I've been on hiatus.  
Sure, I'd like this feature too 👍 I'll see what I can put together.

I'll probably tie it in with the work for #3

**Comment by cmacrae** [comment]
Hey @24unix (& @danielfalbo) as above, this has now been implemented :)  
I'll includ it in the next release (soon!)

**Comment by 24unix** [comment]
Very cool, thx :-)

**Comment by 24unix** [comment]
I'm now on  v1.3.0, how can I enable spacebar only on the main display?

**Comment by cmacrae** [comment]
@24unix As [outlined in the man page](https://github.com/cmacrae/spacebar/blob/v1.3.0/doc/spacebar.asciidoc#5-config), you can set `display` to `main` or `all`

**Comment by 24unix** [comment]
Ah that was just too easy :)

I read "Option to specify only drawing one bar on the main display or multiple bars, one for each display (this aligns with yabai's external_bar option)" and tries some stuff, but nothing worked. Now „spacebar -m config display main" did the trick :) Thank you very much.

**Comment by cmacrae** [comment]
No problem at all :)
