### ISSUE TITLE
restarting spacebar when yabai restarts

### ISSUE THREAD

**Issue by itsdawei** [cmacrae/spacebar#49]
I noticed that when I edit and save my spacebarrc, nothing updates. I had to restart spacebar with brew
```
brew services restart spacebar
```
Is there a way for you to restart spacbar along yabai when restarting yabai with this command?
```
launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"
```
A workaround that I found is to just kill spacebar in the yabai config file:
```
killall spacebar &>/dev/null
```
This will kill spacebar, but it will restart itself immediately, reloading the config file.

BTW: Abosolute great work on this project, hoping to see you take this further!

**Comment by HobbinHood** [comment]
if spacebar is run as a brew related service, what works for yabai also works for spacebar:
```
launchctl kickstart -k "gui/${UID}/homebrew.mxcl.spacebar"
```
if you'd want spacebar to restart after yabai, you could combine both commands in the place where you initiate your restart call, e.g. in the `skhdrc`.

**Comment by cmacrae** [comment]
Hey @itsdawei 👋 As @HobbinHood has pointed out, you can use `launchctl kickstart -k "gui/${UID}/homebrew.mxcl.spacebar"` to do this.

If you're not aware, you can also just simply run the commands you're adding to your spacebarrc and spacebar will live update.
