### ISSUE TITLE
Thank you and are you gonna add more configuration options?

### ISSUE THREAD

**Issue by yanzhang0219** [cmacrae/spacebar#5]
Dear developer,

Thank you so much for your effort in extracting the menu bar from yabai. So far I see we can configure the time format to show the date on the menu bar. I am wondering if you have a plan to add more configuration options? For example, to add some components showing the CPU/MEM/HD info, or the volume info which is probably the must-have component in the menu bar. 

Also, could you please share your plans to develop this amazing and must-have project for yabai users?

Thank you very much. Stay safe and healthy.

**Comment by somdoron** [comment]
Yes, but to do so we need more dynamic blocks modules (each drawing, like the date, would be a block) and you can then choose the blocks you want to display (and their order). 
Anyway, I didn't have time to do it yet.

**Comment by yanzhang0219** [comment]
Thank you. Looking forward to perfecting it.

**Comment by yanzhang0219** [comment]
Hi @somdoron,
yabai has removed its built-in status bar. Spacebar is so far the most promising solution. We really hope you can continue developing it. Thanks.

**Comment by michalens** [comment]
It would be great to have something as extensible as Polybar / i3blocks for MacOS

**Comment by yanzhang0219** [comment]
Wow, extensibility like Polybar/i3blocks is too luxurious. I just hope some basic configs and customizations could be added. I am not familiar with macOS API. Seems I should learn it and make some contributions. Also, I hope there could be other contributors to make this bar sexier. :)
