### ISSUE TITLE
Any documentation for the SLS?

### ISSUE THREAD

**Issue by brorbw** [cmacrae/spacebar#51]
Im looking to implement a couple of features but Im having some trouble when Im encountering SLS

**Comment by cmacrae** [comment]
Hey @brorbw 👋 Could you elaborate a bit?

**Comment by cmacrae** [comment]
I'm guessing you mean the use of the several `SLS*` functions in the code. If so, I believe this is the SkyLight Private Framework. It's undocumented and not intended for public use, as far as I understand. I believe Åsmund likely put a lot of work in to reverse engineer the use of it in yabai. Regardless of how he originally arrived at the code, I'm afraid there's no documentation available. So, I'm going to close this issue :)
