### ISSUE TITLE
Homebrew Install on Big Sur 11.2 fails - "Calling ENV.02 is disabled!"

### ISSUE THREAD

**Issue by flaggerkatt** [cmacrae/spacebar#52]
- Installation on MacOS Big Sur with homebrew fails miserably, throwing message "MethodDeprecatedError: Calling ENV.O2 is disabled! There is no replacement."

Verbose logging from terminal (after downloading and verifying checksum without errors) below:

tar xof /Users/NNN/Library/Caches/Homebrew/downloads/32f3baf9c2018c7a6739719bc33f84473ac306ab6546f4902334e9162444bf9e--spacebar-1.2.1.tar.gz -C /private/tmp/d20210209-23847-11gukq3
cp -pR /private/tmp/d20210209-23847-11gukq3/spacebar-1.2.1/. /private/tmp/spacebar-20210209-23847-8kr4x8/spacebar-1.2.1
chmod -Rf +w /private/tmp/d20210209-23847-11gukq3
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling ENV.O2 is disabled! There is no replacement.
Please report this issue to the cmacrae/formulae tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cmacrae/homebrew-formulae/spacebar.rb:15

**Comment by toinehartman** [comment]
Also occurs for me on Catalina (10.15.7).

**Comment by toinehartman** [comment]
Seems to have to do with a Homebrew update. Please refer to https://github.com/cmacrae/homebrew-formulae/pull/4 for context and solution.

**Comment by cmacrae** [comment]
Fix merged
