### ISSUE TITLE
Shell output not refreshing

### ISSUE THREAD

**Issue by johnallen3d** [cmacrae/spacebar#59]
I'm trying out the latest changes from `master` and I have been able to display output from a shell script but it's static. I had assumed it would refresh on a regular interval. Here's the configuration I have:

```sh
spacebar -m config title                off
spacebar -m config center_shell_command "~/.config/spacebar/mpd"
spacebar -m config center_shell         on
```

This script uses `mpc` and echos a simple string showing my currently playing music.

---

On a somewhat related note. When I enable the above configuration my bar never renders completely. Most times my `clock_icon` is not visible. Occasionally my `power_icon_strip` will be missing. Whenever I start up `spacebar` the center shows the current app title and then changes to output from my shell script. Sometimes it doesn't make that transition (app title stays visible).

I've tried running with the `--verbose` flag but as far as I can tell all is well from that output.

```sh
❯ ./bin/spacebar --verbose
process_is_observable: loginwindow was marked as agent! ignoring..
...
process_is_observable: yabai was marked as background only! ignoring..
process_is_observable: spacebar was marked as background only! ignoring..
EVENT_HANDLER_DAEMON_MESSAGE: config text_font San Francisco Display:Medium:14.0
EVENT_HANDLER_DAEMON_MESSAGE: config icon_font FontAwesome:Regular:14.0
EVENT_HANDLER_DAEMON_MESSAGE: config background_color 0xff2E3440
EVENT_HANDLER_DAEMON_MESSAGE: config space_icon_color 0xff5e81ac
EVENT_HANDLER_DAEMON_MESSAGE: config foreground_color 0xffd8dee9
EVENT_HANDLER_DAEMON_MESSAGE: config power_icon_color 0xffd8dee9
EVENT_HANDLER_DAEMON_MESSAGE: config battery_icon_color 0xffd8dee9
EVENT_HANDLER_DAEMON_MESSAGE: config clock_icon_color 0xffd8dee9
EVENT_HANDLER_DAEMON_MESSAGE: config dnd_icon_color 0xffbf616a
EVENT_HANDLER_DAEMON_MESSAGE: config position top
EVENT_HANDLER_DAEMON_MESSAGE: config spacing_right 20
EVENT_HANDLER_DAEMON_MESSAGE: config title off
EVENT_HANDLER_DAEMON_MESSAGE: config center_shell_command ~/.config/spacebar/mpd
EVENT_HANDLER_DAEMON_MESSAGE: config center_shell on
EVENT_HANDLER_DAEMON_MESSAGE: config space_icon_strip       
EVENT_HANDLER_DAEMON_MESSAGE: config power_icon_strip  
EVENT_HANDLER_DAEMON_MESSAGE: config space_icon 
EVENT_HANDLER_DAEMON_MESSAGE: config clock_icon 
```

I realize that this implementation is brand new and there are likely kinks to work out. I thought it might be valuable to report back some real world experiences.

**Comment by strafe** [comment]
The bar _should_ refresh every 5 seconds, it does so for me with the new features.
https://github.com/cmacrae/spacebar/blob/c9305ddf33f182d75738a12246b8fcf30f0ee813/src/bar.c#L540-L542

**Comment by cmacrae** [comment]
Hey @johnallen3d 👋🏻 As @strafe has pointed out, it is supposed to refresh every 5s

In my preliminary testing, it's been working as expected.  
Have you ensured, as per the documentation, that the command returns output promptly?

Perhaps you could share the config you're using with spacebar and the mpd script?

The title bug sounds weird. If you're using the centre shell output, you shouldn't be able to use the two in tandem (you have to turn the title off to be able to turn the centre shell on).
Are you using the latest master commit?

As for the other parts disappearing, I wonder if it's got something to do with the shell output. It's necessary to strip white space if your command happens to include any tabs, etc.

Thanks for reporting this!

**Comment by johnallen3d** [comment]
Thanks for the input @strafe and @cmacrae. I must be doing something wrong. To eliminate any weirdness in my script I've changed my `center_shell_command` to just `"date"` but I see the same behavior (including the time not refreshing). 🤔 

Here's my complete configuration after removing the script from the equation:

```sh
#!/usr/bin/env sh

PATH=$HOME/development/technekes/src/forks/spacebar/bin:$PATH

# bar settings
spacebar -m config text_font           "San Francisco Display:Medium:14.0"
spacebar -m config icon_font           "FontAwesome:Regular:14.0"
spacebar -m config background_color    0xff2E3440
spacebar -m config space_icon_color    0xff5e81ac
spacebar -m config foreground_color    0xffd8dee9
spacebar -m config power_icon_color    0xffd8dee9
spacebar -m config battery_icon_color  0xffd8dee9
spacebar -m config clock_icon_color    0xffd8dee9
spacebar -m config dnd_icon_color      0xffbf616a
spacebar -m config position            top
spacebar -m config spacing_right       20

spacebar -m config title                off
spacebar -m config center_shell         on
spacebar -m config center_shell_command "date"

spacebar -m config space_icon_strip        
spacebar -m config power_icon_strip   
spacebar -m config space_icon        
spacebar -m config clock_icon        
spacebar -m config dnd_icon          
spacebar -m config clock_format      "%Y-%m-%d %H:%M"

echo "spacebar configuration loaded.."
```

**Comment by strafe** [comment]
Seems like it only happens for me when `clock_format` is set. Also noticed that even though this has nothing to do with the issue here, it seems the wrong thing is being printed out when setting the clock format:
https://github.com/cmacrae/spacebar/blob/c9305ddf33f182d75738a12246b8fcf30f0ee813/src/message.c#L229

**Comment by johnallen3d** [comment]
Thanks for that troubleshooting tip @strafe! I played around with commenting and uncommenting a bunch of config options and I seem to have something work. As long as I set the `center_shell*` options last. 🤷‍♂️ 

Regarding still seeing the app title, here's what I'm seeing. I _always_ see the app title (for some period of time). If I move `title off` to the top of the file I see it for a fraction of a second, then nothing in that place, then there's a pause (5s?) then I see my shell output. Not a complaint, just reporting on behavior. I'm certainly not planning on restarting my bar on a regular basis. 😉

**Comment by strafe** [comment]
I haven't looked at all but that sounds expected I believe. The bar gets rendered and your config gets set line by line immediately after so you see it with the default font and other features for a very minimal amount of time. Also does seem the shell commands get executed every 5 seconds after startup but not on startup/config options which could be a nice improvement.

**Comment by cmacrae** [comment]
Thanks for the info & input on this, guys 🙇   
I perhaps should've kept it specific to the feature, but I've implemented what I believe are some improvements/fixes on the `feature/spaces_for_all_displays` branch that address these issues.

I've confirmed the above shared example config which @johnallen3d reported wasn't working is now working as expected when using the branch above.

I'll be merging that one shortly, when the feature is ready, but feel free to test from there in the meantime!

**Comment by johnallen3d** [comment]
Thanks for working on this @cmacrae! I just tried out this branch with the configuration I had working on `master` and now I'm seeing "center shell" printed out. 🤔 

<img width="261" alt="CleanShot 2021-04-07 at 08 50 30@2x" src="https://user-images.githubusercontent.com/184915/113869111-5acd2780-977e-11eb-9dbc-f55381c7eeb5.png">

**Comment by cmacrae** [comment]
Is that in the centre of the bar?  
Yeah, I'm playnig around with default settings set by the bar manager's init function.  

That's the default you should see when turning on with `spacebar -m config center_shell on`.  
It should update when you change `center_shell_command`

That said... there are some weird bugs going on with this at the moment 🐛 I'm just trying to work out the kinks

**Comment by johnallen3d** [comment]
Yes, sorry, that is the center of my bar. Understood that there are some kinks to work out. I'm happy to test further if/when you have updates.

**Comment by cmacrae** [comment]
Thanks! Really appreciate your testing 🙇

**Comment by cmacrae** [comment]
Alright, I just force pushed some fixes to the `feature/spaces_for_all_displays` branch @johnallen3d - take that for a spin when you've got a moment. I _think_ that should have solved the issues we've been seing 🤞

**Comment by johnallen3d** [comment]
Getting closer! The configuration that I currently have works on both this branch and `master`. However, _if_ I try to set `center_shell on` "early on" in my config file things get weird. As long as `center_shell` related commands come last then I'm good to go. 🤔

**Comment by cmacrae** [comment]
Hmmm, yep, I'm seeing the same behaviour 🤨   
Well at least it gives me a consistent testing scenario!

**Comment by cmacrae** [comment]
Alright, as per the above commit (which is now on master), I _think_ this is fixed. At least, in my preliminary testing, things are looking good. I can set the following as my first 3 `spacebarrc` entries and the bar finishes initialising as it should:
```
spacebar -m config title off
spacebar -m config center_shell_command date
spacebar -m config center_shell on
```

Let me know if it's looking better for you too, @johnallen3d 🙇

**Comment by johnallen3d** [comment]
I was just about to report back what you added in your edit! At first all was well then `error running command`. So close!

**Comment by cmacrae** [comment]
I've narrowed it down to a side effect of `bar_refresh` (which invokes `set_shell_outputs`) being called too frequently.

For instance, there's an event loop that watches for window changes. If you switch windows really frequently with the latest shell output function, after a few seconds, you'll reach the `error running command`.

I'll have to think about how best to tackle this. I had implemented a second timer loop to just run/set the shell output, but I ran into some locking issues, so ended up just adding the refresh operation into `bar_refresh`.

I think that was likely the root cause of the initial problem this issue was describing, haha.

I'll keep trying to squash this, as I really want to get this feature ready for the next release :)

**Comment by cmacrae** [comment]
Alright, let's see where the above commit gets us ☝️  
I re-implemented the separate timer loop. I realised a stupid mistake I'd made when I did it the first time round: I never pulled out calls to `bar_refresh`, which presented the locking issues.

This new timer runs every 5 seconds and is handled separately from other refresh operations :)

**Comment by johnallen3d** [comment]
Running the latest now. Switching windows as fast as I can and everything is working great. 🎉 Thanks for working through this @cmacrae!

**Comment by cmacrae** [comment]
Nice! Glad to hear it's working better - thank you for all your help debugging 🙇 It's been really helpful.

Sadly, there's still one more bug to squash on all this: seemingly, when plugging in another display, the `error running command` string is getting returned and not replaced even after the event loop cycles. So, I'll have to dig into that too 🐛  

I'm going to leave this issue open as a waypoint for handling all issues around this stuff

**Comment by koekeishiya** [comment]
@cmacrae 

I think the real bug is that you never release the process handle when a shell command is completed, before returning:
https://github.com/cmacrae/spacebar/blob/master/src/bar_manager.c#L488, causing the OS process table to hit its limit.

**Comment by cmacrae** [comment]
Oh hey @koekeishiya 👋 Thanks for chiming in here!  
Ah okay, cool - thank you for the pointer. I'm still not familiar enough with C that I wouldn't have stumbled upon that other than by chance. Makes sense and certainly a pretty horrible bug to have introduced 😅

**Comment by cmacrae** [comment]
Alright, with that pointer from @koekeishiya 🙇 I think it's working now!

**Comment by cmacrae** [comment]
After some pretty rigorous testing, it's held up. Given how this feature has gone though, I'm going to leave this issue open for a little longer before release, juuuust to be sure.

**Comment by johnallen3d** [comment]
For what it's worth, I've been running the latest for ~30m without issue. 👍

**Comment by cmacrae** [comment]
Alright, I'm going to consider this fixed 🕺   
Thanks so much for all the input & testing, people! 🙌
