### ISSUE TITLE
Re-think documentation updates for upcoming features

### ISSUE THREAD

**Issue by cmacrae** [cmacrae/spacebar#61]
As outlined in #60, it's pretty confusing that I update the example configs/documentation as I merge unreleased features into the `master` branch. This is the documentation users read when visiting the project and of course it details how to install spacebar via Homebrew/Nix, who's available version won't align with that documentation.

This makes for a bad user experience. Documentation/example changes should come with the relevant feature release.

**Comment by muhammad-saleh** [comment]
Why do unreleased features merged into master?
I guess there should be separate branches for releases and master should only contain the stable channel (currently released version)
There could be a `develop` branch where all of the new features should be merged into and when you're ready to release just merge develop into master?

**Comment by cmacrae** [comment]
@muhammad-saleh Because that's how I like to work. There is [a note in the README](https://github.com/cmacrae/spacebar#releases-and-branches) regarding this.

The master branch in many projects is considered "bleeding-edge". You will often find projects merging unreleased features into master ahead of release.

Personally this is how I opt to work and probably how I will continue. However, I appreciate the confusion of the documentation being updated before release - which is what this issue is for

**Comment by muhammad-saleh** [comment]
@cmacrae oh sorry then, I missed that!

**Comment by cmacrae** [comment]
@muhammad-saleh No need for apologies :) I appreciate your input on the matter 👍

**Comment by strafe** [comment]
Could start using the wiki like yabai
