### ISSUE TITLE
Bar position

### ISSUE THREAD

**Issue by JonathanHuot** [cmacrae/spacebar#7]
I think it will be great to have the choice of selecting the position of the status bar. I will not expect left and right, but I think bottom can be helpful. 

e.g. yabai -m config status_bar_position bottom

(cloned from https://github.com/koekeishiya/yabai/issues/484)

**Comment by ryuta69** [comment]
I hope this feature so much as well.

**Comment by cmacrae** [comment]
I just opened #24 which implements this :) 

Courtesy tag:  
@JonathanHuot @ryuta69 @yanzhang0219 @srsholmes @omar25h @isometry  
(Sorry if this is no longer of interest to any of you, I figured I'd tag based on the 👍's)

**Comment by cmacrae** [comment]
This feature is included in the [v1.0.0 release](https://github.com/cmacrae/spacebar/releases/tag/v1.0.0) 🎉
