### ISSUE TITLE
[Request]Force Shell script to run

### ISSUE THREAD

**Issue by ericlovesmath** [cmacrae/spacebar#76]
With release of 1.3.0, I can test out shell scripts on spacebar.

The first thing I tried is to make a [keyboard layout script](https://github.com/cmacrae/spacebar/discussions/70#discussioncomment-662819), but then I realized it only updated every 5 seconds, causing massive delay.

It would be nice to have some function like `spacebar -m config --force-update right_shell`

Maybe this could be supported in the future?

**Comment by cmacrae** [comment]
Hey @ericlovesmath 👋 Thanks for the request.  
At the moment, I'm taking a break from implementing features/fixes on spacebar as I'm in the middle of a complete rewrite.

The good news is that I've already implemented per module refresh timers in the new version. For example, here's the clock module redrawing every second:
![module_refresh](https://user-images.githubusercontent.com/3392199/116214720-e19e7000-a73e-11eb-84f7-f321d87a24fd.gif)

That said, you don't need a `--force-update` flag to achieve what you want in this manner (calling a command to update the shell output more frequently as a work around). The shell outputs are refreshed on a 5 second timer, but also when they are set. So, as a hack, you can do something like this:  
```
while sleep 1 ; do spacebar -m config left_shell_command "date" ; done
```
![current_refresh](https://user-images.githubusercontent.com/3392199/116215866-f7f8fb80-a73f-11eb-83f5-476ac60425d2.gif)

Hopefully this is a satisfactory workaround until the new version is released :)
