### ISSUE TITLE
Running as root is not allowed

### ISSUE THREAD

**Issue by Zaitam** [cmacrae/spacebar#89]
Started to have the error `spacebar: running as root is not allowed! abort..`

I am on MacOS 11.4 using HomeBrew

This affects on:
1. Can't change the preferences with the file because it doesn't finish to run
2. Data on the bar doesn't update

**Comment by spaceneb** [comment]
I understand the issue, but why would you need to run as root? Especially on macOS and (probably) in a desktop environment?

**Comment by Zaitam** [comment]
Sorry, this was long ago I don't remember exactly the problem but think I was the log of home brew?
