### ISSUE TITLE
resize bar height

### ISSUE THREAD

**Issue by dsanson** [cmacrae/spacebar#9]
The simplest version of this request:
-   a setting to adjust bar height

A more complicated feature request:
-   automatically adjust bar height by font size (and, I guess, offer a command that reports this, so that yabai's top_padding can be adjusted to match)

**Comment by cmacrae** [comment]
I've added a `height` option and released it in [v1.1.0](https://github.com/cmacrae/spacebar/releases/tag/v1.0.0) :)
