### ISSUE TITLE
Feature Request: display spacebar on the top of any windows

### ISSUE THREAD

**Issue by c4710n** [cmacrae/spacebar#97]
First, thank you for developing this cool stuff.
---

Recently, I changed my workflow. I started displaying window in maximium style:
+ hide menubar
+ hide dock

> Not the native fullscreen of macOS.

Just like this:
<img src="https://user-images.githubusercontent.com/59962222/151013087-200fd6cc-94cb-40b8-8d32-bc5f7c8229bc.png" width="500" />

But I still care about battery usage, I want to show it on the right corner of screen, like (the red box):
<img src="https://user-images.githubusercontent.com/59962222/151014013-6c97dec4-6a58-43ba-8454-e351d1cfc9f9.png" width="500" />

Currently, spacebar is displayed on the bottom of any windows, so spacebar will be hidden by the Firefox window.

Is there any way to display it on the top of any windows?

**Comment by ibehnam** [comment]
is there any way to do that right now?
